# Perfil de Desenvolvimento
spring.config.activate.on-profile=dev

# Database Local
spring.datasource.url=jdbc:postgresql://localhost:5432/db_portal_api
spring.datasource.username=apiportal
spring.datasource.password=apiportal123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keycloak
keycloak.url=http://localhost:8180
keycloak.realm=portal-api
keycloak.client-id=portal-api
keycloak.client-secret=RNEWX0EvC41j5ytpCg9Qw6EuhcEJdixn
keycloak.admin.username=admin
keycloak.admin.password=admin123
keycloak.admin.client-id=admin-cli

# Frontend
app.frontend.url=http://localhost:4200

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
